MEMMAP_TYPE_USABLE = 1
MEMMAP_TYPE_RESERVED = 2
MEMMAP_TYPE_ACPI_RECLAIMABLE = 3
MEMMAP_TYPE_ACPI_NVS = 4
MEMMAP_TYPE_BAD = 5

MEMMAP_TYPE_SUPERVISOR = 0x1000
MEMMAP_TYPE_BOOTLOADER = 0x1001

struct memmap_entry
	.base dd ?
	.length dd ?
	.type dd ?
end struct
